<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
<!ELEMENT contabilidad (transaccion*)>
<!ELEMENT transaccion (ingreso|gasto)>
<!ELEMENT ingreso (apunte)>
<!ELEMENT gasto (apunte)>
<!ELEMENT apunte (fecha, cantidad, concepto)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
<transaccion>
<ingreso>
<apunte>
<fecha>24 de febrero de 2019</fecha>
<cantidad>1800,00 €</cantidad>
<concepto>Salario</concepto>
</apunte>
</ingreso>
</transaccion>
<transaccion>
<gasto>
<apunte>
<fecha>28 de febrero de 2019</fecha>
<cantidad>74,25 €</cantidad>
<concepto>Recibo luz</concepto>
</apunte>
</gasto>
</transaccion>
</contabilidad>