<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
<!ELEMENT colores (color*)>
<!ELEMENT color (nombreSvg, codigo)>
<!ELEMENT nombreSvg (#PCDATA)>
<!ELEMENT codigo (hex, rgb, cmyk)>
<!ELEMENT hex (#PCDATA)>
<!ELEMENT rgb (#PCDATA)>
<!ELEMENT cmyk (#PCDATA)>
]>

<colores>
<color>
<nombreSvg>Morado</nombreSvg>
<codigo>
<hex>#800080</hex>
<rgb>r:128 g:0 b:128</rgb>
<cmyk>0-100-100-50</cmyk>
</codigo>
</color>
<color>
<nombreSvg>Verde claro</nombreSvg>
<codigo>
<hex>#00FF007F</hex>
<rgb>r:0 g:255 b:0</rgb>
<cmyk>100-0-100-0</cmyk>
</codigo>
</color>
</colores>

