<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE favoritos [ 
<!ELEMENT favoritos (marcadores)>
<!ELEMENT marcadores (marcador*)>
<!ELEMENT marcador (nombre,uri)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
]>

<favoritos>
<marcadores>
<marcador>
<nombre>W3C</nombre>
<uri>http://www.w3.org/</uri>
</marcador>
<marcador>
<nombre>Web HypertextApplicationTechnologyWorkingGroup(WHATWG)</nombre>
<uri>http://www.whatwg.org/</uri>
</marcador>
</marcadores>
</favoritos>